ALTER TABLE `matches` ADD `game_version` text;--> statement-breakpoint
ALTER TABLE `matches` ADD `map_id` integer;--> statement-breakpoint
ALTER TABLE `matches` ADD `platform_id` text;--> statement-breakpoint
ALTER TABLE `matches` ADD `game_type` text;--> statement-breakpoint
ALTER TABLE `matches` ADD `end_of_game_result` text;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `gold_earned` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `total_damage_dealt_to_champions` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `total_damage_taken` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `total_heal` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `total_damage_shielded_on_teammates` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `wards_placed` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `wards_killed` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `control_wards_placed` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `double_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `triple_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `quadra_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `penta_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `first_blood_kill` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `turret_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `objectives_stolen` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `damage_per_minute` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `gold_per_minute` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `kda` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `kill_participation` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `team_damage_percentage` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `vision_score_per_minute` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `solo_kills` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `skillshots_dodged` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `skillshots_hit` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `time_played` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `total_time_spent_dead` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item0` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item1` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item2` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item3` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item4` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item5` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `item6` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `summoner1_id` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `summoner2_id` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `primary_rune` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `secondary_rune` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `queue_id` integer;--> statement-breakpoint
ALTER TABLE `player_matches` ADD `game_version` text;