CREATE TABLE `champion_benchmarks` (
	`champion_id` integer NOT NULL,
	`champion_name` text NOT NULL,
	`role` text NOT NULL,
	`tier` text NOT NULL,
	`games_analyzed` integer DEFAULT 0 NOT NULL,
	`avg_kills` integer,
	`avg_deaths` integer,
	`avg_assists` integer,
	`avg_kda` integer,
	`win_rate` integer,
	`avg_cs_per_min` integer,
	`avg_gold_per_min` integer,
	`avg_damage_per_min` integer,
	`avg_damage_share` integer,
	`avg_vision_score_per_min` integer,
	`avg_wards_placed` integer,
	`avg_control_wards_placed` integer,
	`avg_kill_participation` integer,
	`avg_solo_kills` integer,
	`avg_skillshots_hit` integer,
	`avg_skillshots_dodged` integer,
	`avg_lane_minions_first_10_min` integer,
	`avg_early_gold_advantage` integer,
	`avg_turret_plates_taken` integer,
	`avg_dragon_takedowns` integer,
	`updated_at` integer NOT NULL,
	PRIMARY KEY(`champion_id`, `role`, `tier`)
);
